// Listes fictives utilisées pour anonymiser raisons sociales, noms et prénoms.
// Les valeurs sont volontairement inventées (jeu de données neutre, francophone).

export const COMPANY_NAMES: readonly string[] = [
  'Aurora Industries',
  'Beluga Conseil',
  'Cèdre & Associés',
  'Datavise Solutions',
  'Edelweiss Logistique',
  'Forêt Numérique',
  'Galaxie Holdings',
  'Hélios Énergie',
  'Iris Mécanique',
  'Jasmin Audit',
  'Korus Studio',
  'Lumiverse',
  'Mistral Habitat',
  'Néphélis Bio',
  'Octans Aérospatial',
  'Pampero Conseil',
  'Quinoa Bistronomie',
  'Rivage Maritime',
  'Sapientia Formation',
  'Topaze Construction',
  'Ursa Mobilité',
  'Vertige Médias',
  'Wagram Patrimoine',
  'Xylos Bois & Co',
  'Yarrow Cosmétiques',
  'Zenith Robotique',
  'Acacia Distribution',
  'Banyan Capital',
  'Cassiopée Conseil',
  'Delta Falaise',
  'Emeraude Verre',
  'Falco Sécurité',
  'Galène Pharma',
  'Heliotrope Mode',
  'Indigo Édition',
  'Joubarbe Services',
  'Kaolin Industries',
  'Lichen Recherche',
  'Magnolia Habitat',
  'Nimbus Cloud',
  'Onyx Logistique',
  'Phare Concept',
  'Quadrige Maritime',
  'Roseraie Évènements',
  'Sereno Café',
  'Tilia Bois',
  'Ulysse Voyages',
  'Verveine Boulangerie',
  'Wildflower Brasserie',
  'Xanthe Métaux',
  'Yatagan Cybersécurité',
  'Zélée Naval',
  'Adage Imprimerie',
  'Bambou Restauration',
  'Comète Édition',
  'Diapason Audio',
  'Erebos Industries',
  'Fjord Énergies',
  'Granit Foncier',
  'Hibiscus Évènement',
  'Iode Marine',
  'Jaspe Joaillerie',
  'Kintsugi Restauration',
  'Lampion Spectacle',
  'Méridien Conseil',
  'Nautile Numérique',
  'Opaline Verrerie',
  'Pavot Communication',
  'Quartz Solutions',
  'Rosée Distribution',
  'Sycomore Habitat',
  'Tournesol Énergie',
  'Ubac Montagne',
  'Volubilis Mode',
  'Wapiti Aventure',
  'Xerus Construction',
  'Yucca Importation',
  'Zéphyr Aéronautique',
  'Albâtre Pierre',
  'Brume Naval',
  'Caravelle Voyages',
  'Dahlia Cosmétiques',
  'Embrun Maritime',
  'Faisan Habillement',
  'Glycine Patrimoine',
  'Horizon Conseil',
  'Iguane Sport',
  'Jadis Antiquités',
  'Kaléido Design',
  'Laguna Évènement',
  'Mosaïque Architecture',
  'Néroli Parfums',
  'Origan Restauration',
  'Pyrale Industries',
  'Quenelle Bistro',
  'Refuge Hôtellerie',
  'Saphir Tech',
  'Trèfle Édition',
  'Ursin Pêche',
  'Volute Verrerie',
  'Wabi Architecture',
  'Xinou Pharma',
  'Yuzu Restauration',
  'Zinzolin Mode',
];

export const FIRST_NAMES: readonly string[] = [
  'Adrien',
  'Alice',
  'Amélie',
  'Anaïs',
  'Antoine',
  'Apolline',
  'Arnaud',
  'Aurélien',
  'Aurore',
  'Baptiste',
  'Béatrice',
  'Benjamin',
  'Camille',
  'Caroline',
  'Charlotte',
  'Chloé',
  'Christine',
  'Clara',
  'Claire',
  'Clément',
  'Constance',
  'Corentin',
  'Damien',
  'Daphné',
  'David',
  'Delphine',
  'Diane',
  'Dorian',
  'Eléonore',
  'Élise',
  'Emma',
  'Emmanuel',
  'Estelle',
  'Étienne',
  'Eugène',
  'Fabien',
  'Félicie',
  'Florence',
  'Florent',
  'François',
  'Gabriel',
  'Gabrielle',
  'Gaspard',
  'Gauthier',
  'Geneviève',
  'Guillaume',
  'Hadrien',
  'Hélène',
  'Henri',
  'Hortense',
  'Hugo',
  'Inès',
  'Iris',
  'Isaac',
  'Isabelle',
  'Jeanne',
  'Jérémy',
  'Joachim',
  'Jonathan',
  'Joséphine',
  'Judith',
  'Julie',
  'Julien',
  'Justine',
  'Karim',
  'Kévin',
  'Laetitia',
  'Laure',
  'Léa',
  'Léna',
  'Léon',
  'Léonie',
  'Lila',
  'Loïc',
  'Lola',
  'Louis',
  'Louise',
  'Lucas',
  'Lucie',
  'Maël',
  'Manon',
  'Margaux',
  'Marine',
  'Mathieu',
  'Mathilde',
  'Maxime',
  'Mélanie',
  'Mila',
  'Nathan',
  'Nathalie',
  'Nicolas',
  'Noémie',
  'Octave',
  'Olivia',
  'Olivier',
  'Ophélie',
  'Oscar',
  'Pascal',
  'Paul',
  'Paulin',
  'Pauline',
  'Pénélope',
  'Pierre',
  'Quentin',
  'Raphaël',
  'Romane',
  'Roxane',
  'Sacha',
  'Salomé',
  'Samuel',
  'Sandra',
  'Sébastien',
  'Sidonie',
  'Simon',
  'Solène',
  'Sophie',
  'Stanislas',
  'Sylvain',
  'Tanguy',
  'Thaïs',
  'Théo',
  'Théodore',
  'Thibault',
  'Timéo',
  'Tom',
  'Valentine',
  'Vincent',
  'Violette',
  'Virgile',
  'Yann',
  'Yves',
  'Zélie',
  'Zoé',
];

export const LAST_NAMES: readonly string[] = [
  'Albert',
  'Antoine',
  'Arnaud',
  'Aubert',
  'Aubry',
  'Bailly',
  'Barbier',
  'Barre',
  'Baudouin',
  'Berger',
  'Bernard',
  'Bertin',
  'Besson',
  'Bigot',
  'Blanc',
  'Blanchard',
  'Bonnet',
  'Bouchard',
  'Boucher',
  'Boulanger',
  'Bourdon',
  'Bourgeois',
  'Boyer',
  'Brun',
  'Brunet',
  'Caron',
  'Carpentier',
  'Cartier',
  'Charpentier',
  'Chevalier',
  'Clément',
  'Cohen',
  'Colin',
  'Collet',
  'Cordier',
  'Couturier',
  'Da Silva',
  'David',
  'Delahaye',
  'Denis',
  'Deschamps',
  'Dubois',
  'Duchêne',
  'Duhamel',
  'Dumas',
  'Dumont',
  'Dupin',
  'Dupont',
  'Dupré',
  'Durand',
  'Étienne',
  'Évrard',
  'Faure',
  'Fernandez',
  'Ferrand',
  'Ferreira',
  'Fontaine',
  'Fournier',
  'Gaillard',
  'Garcia',
  'Garnier',
  'Gauthier',
  'Gauvin',
  'Georges',
  'Gérard',
  'Gilbert',
  'Giraud',
  'Gomez',
  'Grégoire',
  'Guérin',
  'Guichard',
  'Guillaume',
  'Guillet',
  'Hamon',
  'Hardy',
  'Henry',
  'Herbert',
  'Hubert',
  'Humbert',
  'Imbert',
  'Jacquet',
  'Joly',
  'Jourdain',
  'Julien',
  'Lacombe',
  'Lacroix',
  'Lafleur',
  'Lagarde',
  'Lambert',
  'Lamy',
  'Lange',
  'Laporte',
  'Lasserre',
  'Laurent',
  'Lavergne',
  'Lebrun',
  'Lecomte',
  'Leduc',
  'Lefèvre',
  'Legrand',
  'Lemaire',
  'Lemoine',
  'Léonard',
  'Leroy',
  'Levasseur',
  'Lévêque',
  'Louvet',
  'Lucas',
  'Mahé',
  'Maillard',
  'Marchal',
  'Marchand',
  'Maréchal',
  'Marty',
  'Masson',
  'Mathieu',
  'Maurice',
  'Mercier',
  'Meunier',
  'Michel',
  'Millet',
  'Molina',
  'Monnier',
  'Morel',
  'Morin',
  'Moulin',
  'Munoz',
  'Nguyen',
  'Nicolas',
  'Nogueira',
  'Noiret',
  'Nogues',
  'Olivier',
  'Pages',
  'Paris',
  'Pasquier',
  'Payet',
  'Pelletier',
  'Pereira',
  'Perez',
  'Perrin',
  'Petit',
  'Picard',
  'Pichon',
  'Pierre',
  'Pinto',
  'Piquet',
  'Poirier',
  'Pontier',
  'Pottier',
  'Poulain',
  'Prévost',
  'Prudhomme',
  'Renard',
  'Renaud',
  'Reynaud',
  'Ribeiro',
  'Richard',
  'Riou',
  'Robert',
  'Robin',
  'Roche',
  'Rocher',
  'Rodrigues',
  'Roger',
  'Rolland',
  'Rossi',
  'Rousseau',
  'Roussel',
  'Roux',
  'Roy',
  'Salvador',
  'Sanchez',
  'Sauvage',
  'Schmitt',
  'Schneider',
  'Sellier',
  'Simon',
  'Simonet',
  'Soulier',
  'Tessier',
  'Thomas',
  'Tissier',
  'Torres',
  'Tournier',
  'Vallet',
  'Vasseur',
  'Verdier',
  'Vergne',
  'Vidal',
  'Vincent',
  'Voisin',
  'Weber',
];

/**
 * Pool of real-world francophone cities used to anonymise city fields.
 * Using real (mostly French and European) cities keeps the substitution
 * realistic: it preserves the "looks like a city" signal in downstream
 * tooling without leaking the original geography. Cities are public knowledge
 * and not personal data, so picking from the real world is safe here.
 */
export const CITIES: readonly string[] = [
  'Paris',
  'Marseille',
  'Lyon',
  'Toulouse',
  'Nice',
  'Nantes',
  'Strasbourg',
  'Montpellier',
  'Bordeaux',
  'Lille',
  'Rennes',
  'Reims',
  'Saint-Étienne',
  'Toulon',
  'Le Havre',
  'Grenoble',
  'Dijon',
  'Angers',
  'Nîmes',
  'Villeurbanne',
  'Saint-Denis',
  'Aix-en-Provence',
  'Le Mans',
  'Clermont-Ferrand',
  'Brest',
  'Tours',
  'Limoges',
  'Amiens',
  'Annecy',
  'Perpignan',
  'Besançon',
  'Boulogne-Billancourt',
  'Orléans',
  'Metz',
  'Rouen',
  'Mulhouse',
  'Caen',
  'Nancy',
  'Saint-Paul',
  'Tourcoing',
  'Roubaix',
  'Argenteuil',
  'Montreuil',
  'Nanterre',
  'Avignon',
  'Vitry-sur-Seine',
  'Créteil',
  'Poitiers',
  'Dunkerque',
  'Asnières-sur-Seine',
  'Courbevoie',
  'Versailles',
  'Pau',
  'Colombes',
  'Aulnay-sous-Bois',
  'La Rochelle',
  'Champigny-sur-Marne',
  'Rueil-Malmaison',
  'Antibes',
  'Saint-Maur-des-Fossés',
  'Calais',
  'Cannes',
  'Béziers',
  'Colmar',
  'Bourges',
  'Drancy',
  'Mérignac',
  'Saint-Nazaire',
  'Issy-les-Moulineaux',
  'Levallois-Perret',
  'Quimper',
  'Noisy-le-Grand',
  'Cergy',
  'La Seyne-sur-Mer',
  'Pessac',
  'Valence',
  'Vénissieux',
  'Antony',
  'Clichy',
  'Ivry-sur-Seine',
  'Troyes',
  'Lorient',
  'Niort',
  'Sarcelles',
  'Chambéry',
  'Montauban',
  'Saint-Quentin',
  'Villejuif',
  'Hyères',
  'Beauvais',
  'Cholet',
  'Maisons-Alfort',
  'Pantin',
  'Évry-Courcouronnes',
  'Fréjus',
  'Bondy',
  'Bayonne',
  'Châlons-en-Champagne',
  'Vannes',
  'Évreux',
  'Charleville-Mézières',
  'Brive-la-Gaillarde',
  'Albi',
  // Quelques villes francophones hors France pour la diversité.
  'Bruxelles',
  'Liège',
  'Charleroi',
  'Anvers',
  'Genève',
  'Lausanne',
  'Zurich',
  'Berne',
  'Montréal',
  'Québec',
  'Sherbrooke',
  'Gatineau',
  'Trois-Rivières',
  'Luxembourg',
  'Dakar',
  'Abidjan',
  'Casablanca',
  'Rabat',
  'Tunis',
  'Alger',
];

/**
 * Domain pool used to forge anonymous e-mails. The `.example`, `.test` and
 * `.invalid` TLDs are formally reserved (RFC 2606 / 6761) and cannot be
 * registered — that makes them safe sentinels for fake data.
 */
export const EMAIL_DOMAINS: readonly string[] = [
  'example.com',
  'example.fr',
  'example.org',
  'example.net',
  'mail.example',
  'corp.example',
  'lab.example',
  'demo.example',
  'sample.example',
  'fictif.example',
  'donnees-test.example',
  'anonymous.example',
];

/**
 * Returns a random element from the list, optionally avoiding `exclude`.
 */
export function randomFrom(
  source: readonly string[],
  exclude?: string | null,
): string {
  if (source.length === 0) return '';
  if (source.length === 1) return source[0];
  let pick = source[Math.floor(Math.random() * source.length)];
  let safety = 0;
  while (exclude != null && pick === exclude && safety < 8) {
    pick = source[Math.floor(Math.random() * source.length)];
    safety += 1;
  }
  return pick;
}
